monolog:
  channels: ['customchannel']
  handlers:
    main:
      type: fingers_crossed
      action_level: warning
      handler: nested
    customchannel:
      type: fingers_crossed
      action_level: info
      handler: nested
      channels: ['customchannel']
    nested:
      type:  stream
      path:  "php://stderr"
      level: debug
    console:
      type:  console
